# Generated by Django 5.2 on 2025-05-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('user_contect_number', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_password', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(default='customer', max_length=20)),
            ],
        ),
    ]
