# Generated by Django 5.2 on 2025-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='user_contect_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
