# Generated by Django 5.1.7 on 2025-05-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customeruser_user_contect_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='user_contect_number',
            new_name='user_contact_number',
        ),
    ]
