# Generated by Django 5.2 on 2025-05-01 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('s_time', models.TimeField(blank=True, null=True)),
                ('e_time', models.TimeField(blank=True, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('business_reg_id', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(default='restaurant', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Dine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dine_type', models.CharField(choices=[('Deshi traditional restaurant', 'Deshi traditional restaurant'), ('Biriyani house', 'Biriyani house'), ('cafe lounge', 'cafe lounge'), ('buffet', 'buffet'), ('fine dining', 'fine dining'), ('rooftop dining', 'rooftop dining'), ('seafood restaurant', 'seafood restaurant'), ('fast food & burger joint', 'fast food & burger joint'), ('family dining', 'family dining')], max_length=150)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
