# Generated by Django 5.1.7 on 2025-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
