# Generated by Django 5.2 on 2025-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_table_list_date_alter_table_list_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_list',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
