# Generated by Django 5.2 on 2025-05-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('reservation', '0003_table_list_is_available'),
        ('restaurant', '0003_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table_list',
            unique_together={('restaurant', 'table_no', 'date', 'start_time', 'end_time', 'no_of_people')},
        ),
        migrations.AlterUniqueTogether(
            name='tablereservation',
            unique_together={('user', 'table', 'reserve_date', 'start_time', 'end_time')},
        ),
    ]
