# Generated by Django 5.1.7 on 2025-05-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_table_list_unique_together_and_more'),
        ('restaurant', '0003_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table_list',
            unique_together={('restaurant', 'table_no', 'date', 'start_time', 'end_time')},
        ),
    ]
