# Generated by Django 5.2.1 on 2025-05-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_table_list_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablereservation',
            unique_together=set(),
        ),
    ]
